### ISSUE TITLE
Disable GA and Disqus when served locally

### ISSUE THREAD

**Issue by chipset95** [PanosSakkos/personal-jekyll-theme#100]
Its better if Google Analytics and Disqus are disabled when the the site is served locally. Otherwise it messes with the analytics and disqus creates multiple threads which become difficult to merge later. 

Jekyll maintains an environment variable which can be accessed useking `jekyll.environment` and has the value `production` when deployed on github and `development` when run locally. This can be leveraged in the theme.

I'm already on it. I'll put a PR soon.

**Edit**: 100 issues :stuck_out_tongue:

**Comment by joariasl** [comment]
Now I know the commits by @chipset95. If GitHub run this how production, then it is good.
But is necessary remember this to them, some build their site in local and upload in their own hosting.

**Comment by chipset95** [comment]
@joariasl they would just need to add `JEKYLL_ENV=production` before the jekyll serve in their hosting.
