### ISSUE TITLE
Decide on offset when listing posts

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#102]
Let's vote on the offset that we want when listing posts on archive and tag layouts.

#Offset 1

![offset1](https://dl.dropboxusercontent.com/u/8522559/personal-jekyll-theme/bugs/offset1.png)

#Offset 2

![offset1](https://dl.dropboxusercontent.com/u/8522559/personal-jekyll-theme/bugs/offset2.png)

**Comment by chipset95** [comment]
Offset 1

**Comment by joariasl** [comment]
I think that offset 2 is much. I prefer 1.

**Comment by PanosSakkos** [comment]
Offset 1

**Comment by PanosSakkos** [comment]
@njaremko voted for offset 1 on gitter.

Offset 1 it is then :smile: I will track it under a new issue.
