### ISSUE TITLE
Use uniform share buttons

### ISSUE THREAD

**Issue by chipset95** [PanosSakkos/personal-jekyll-theme#111]
As discussed on gitter, I'll be trying new consistent looking share buttons on my page before sending a PR here. Here are a few options:

[Shareaholic](http://sharebuttons.com/)
[RRSSB](https://github.com/kni-labs/rrssb)
[Share for Bootstrap](http://lipis.github.io/bootstrap-social/)

I like RRSSB the most.

**Comment by PanosSakkos** [comment]
Shareaholic's buttons look cheap :yum: 

And between RRSSB and Share for Bootstrap, RRSSB seems to be more active as a project :smile:

**Comment by PanosSakkos** [comment]
I will give a try on RRSSB now :wink:
