### ISSUE TITLE
Swipe Instruction can become covered by Share Buttons

### ISSUE THREAD

**Issue by eiselems** [PanosSakkos/personal-jekyll-theme#122]
Bug: If post has less than about 4 paragraphs the swipe instruction is cover.

Reproduce: Remove a few lines in https://panossakkos.github.io/personal-jekyll-theme/tech/2015/06/27/welcome.html
Result:
![image](https://cloud.githubusercontent.com/assets/5188694/11365280/9e5c104e-92a5-11e5-876f-67c8082c356b.png)

**Comment by eiselems** [comment]
I just tried to apply z-index:1 to <div id="swipe-instruction"> - seems to work like it should.
Can provide a fix later, just need to setup a saas environment.

**Comment by eiselems** [comment]
Update:

realized i don't need to compile anything by myself :smile: 

I only have no clue where to put that
```sass
#swipe-instruction {
    z-index: 1;
}
```
Should we create a new scss file for blog related styles?
Or where should it be placed?

**Comment by PanosSakkos** [comment]
Well spotted! :smile:

Check the fix commit to see the diff :wink:
