### ISSUE TITLE
ruby based scripts under scripts dir don't work on linux (ubuntu)

### ISSUE THREAD

**Issue by portenez** [PanosSakkos/personal-jekyll-theme#129]
The current shebang is

```sh
#!/usr/bin/ruby
```

which is not quite "compliant"

after changing it to 

```sh
#!/usr/bin/env ruby
```

it works. 

I'm using rvm.

**Comment by njaremko** [comment]
there's nothing non-"compliant" about it. By specifying which ruby
executable to use, we prevent inevitable errors that would arise from using
non-standard ruby implementations. The env ruby setup just tells the script
to use the first occurrence of ruby in your path, there's no standard
requiring its use. It's more of a preference than anything.

**Comment by portenez** [comment]
Yeah, I couldn't find the right word, so forget about the word "compliant".  

The issue still remains: that the scripts do not work when using rvm in ubuntu, and that they're solved when using /usr/bin/env ruby. I can see the point of pointing directly to the ruby distribution under /usr/bin, but there's going to be the risk of it not being there. Like when using rvm.

**Comment by njaremko** [comment]
Well, it's up to Panos in the end, but I think that the subset of ruby
users with rvm will know what to change in the scripts, or you can symlink
ruby if you want scripts such as these to always work.
