### ISSUE TITLE
Remove unused CSS classes.

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#13]

**Comment by PanosSakkos** [comment]
@joariasl I think that if we filter the unused CSS classed of bootstrap, instead of retrieving the whole library from CDN, then we will have a better performance gain. Are you interested in investigating this? :smile: I had a look at it in the past, and it seems like it's very easy to filter out all the bootstrap classes that your website is not using.

**Comment by joariasl** [comment]
Performance is increase, this increases the positioning of sites on search engines.
Using CDN currently makes the cache for common resources between sites is used, it is a good option for now.
I will review it when I have time.
Regards.
A link: http://getbootstrap.com/getting-started/#grunt-commands

**Comment by PanosSakkos** [comment]
I agree, but this is an assumption until we actually do a perf test! :smile: 

As they say, "You don't know performance until you measure it" :wink:

**Comment by PanosSakkos** [comment]
@njaremko Any feedback on this enhancement?

**Comment by njaremko** [comment]
Couldn't we just use this? 
http://getbootstrap.com/customize/

Github puts all assets for Github Pages sites onto their CDN, so no need to worry about the lack of CDN.

**Comment by PanosSakkos** [comment]
Nice, I will have a look on the link. 

I'm concerned about what is more efficient:

1) Fetching the whole bootstrap from a CDN (probably)
or
2) Minimize the library in order to get a file with only the needed classes

Of course this cannot be answered without an investigation but this issue is low priority so I keep deprioritizing :cry:

**Comment by altsheets** [comment]
Very good idea. 

Not only because of performance, but also ... I actually had a bit of a hard time trying to figure out which style does what. 
Are really all styles in grayscale.scss being used? (Perhaps some comments in the CSS might help?)

Perhaps I am simply not using the fanciest design tools yet. Is there a way to figure out which CSS classes get applied to an element, e.g. by pointing to it in the browser (some browser extension perhaps)? 

Thanks a lot, and sorry for my slightly off-topic question.

:-)

**Comment by njaremko** [comment]
@PanosSakkos We don't need to worry about our customized version not being on a CDN. Github puts all page assets on their Fastly CDN.

**Comment by joariasl** [comment]
I applied a complete refactor for grayscale.scss. I removed the definitions of original Grayscale theme that are not used in { Personal } theme.

**Comment by joariasl** [comment]
Style color is now configurable:

For example, to emulate @chipset95 theme configure this:

_config.yml:
```yml
background-img: False
```

_sass/_variables.scss:
```scss
// Variables

$primary: #444;
$dark: #fff;
$light: #000;

$header-text-shadow: false;
$header-background-color: #3f51b5;
$navbar-color: #fff;
$navbar-lg-background: #303f9f;
$navbar-lg-collapse-background-color: #303f9f;
$navbar-sm-background-color: $navbar-lg-collapse-background-color;

$social-buttons-color: #fff;
```

**Comment by PanosSakkos** [comment]
@joariasl Great initiative! Usability++! :smiley: :+1: :+1:

**Comment by chipset95** [comment]
I actually did not provide any background image, wrote new sass variables using [Material Pallete](http://www.materialpalette.com/) and used them in `grayscale.scss`, nothing very fancy! :stuck_out_tongue_winking_eye:
