### ISSUE TITLE
Support multiple categories and discovery

### ISSUE THREAD

**Issue by joariasl** [PanosSakkos/personal-jekyll-theme#132]
Actually the cathegory folders are show 404 error page, a good implementation is show all posts from this category and include the link in the name showed in the posts list and page.
It is possible using the site.categories.CATEGORY variable...

**Comment by PanosSakkos** [comment]
We should definitely support multiple categories :) 
And we should handle them like we we are handling the hashtags :smile: 

Currently I'm swamped with daytime job and https://github.com/panossakkos/one-passwords, so feel free to jump on this feature if you feel like it :wink:

**Comment by bgoldman** [comment]
The feature I submitted which you merged isn't supporting multiple categories per post, only one category per post. What the feature does support is category links and pages. Are you sure you want to support multiple categories per post though?

**Comment by PanosSakkos** [comment]
yeah this is bad writing. By "multiple categories" I had in my mind exactly what you did :wink: 

It doesn't make much sense to list a post under multiple categories, like you said :wink:
