### ISSUE TITLE
Gtmetrix results

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#135]
A friend showed me this service and we got some reds.

https://gtmetrix.com/reports/panossakkos.github.io/fmRLBokk

Let's discuss it in order to track whatever we decide to take in under issues :smile:

**Comment by njaremko** [comment]
I get an A on mine hahaha, gotta scale those images.

**Comment by PanosSakkos** [comment]
Awesome! :smile: 

@njaremko shouldn't we document how to optimize the pictures? :smile:

**Comment by njaremko** [comment]
It's really up to the user. I generally inspect the element on a full size display and check what size it's rendering at. Then use photoshop/gimp to resize using the best algorithm available. Then run ZopfliPNG on the pngs. Jpeg has a similar program I can't remember the name of, easy to google though.

**Comment by jose-zama** [comment]
This is such a good and handy tool! A good one @PanosSakkos . I agree with @njaremko comments. Even more, there are probably several ways to scale and/or optimize images. And I am not 100% sure but maybe with CSS and media queries, different size images could be served depending on the view port size. 

Anyway, the vanilla theme gets an "A", so I would suggest to close this issue. If the user change the images (and he should) she/he is responsible to maintain the same sizes. An advice/comment should be enough.

**Comment by PanosSakkos** [comment]
@njaremko well the sample site gets an A thanks to you :wink: 

Closing the discussion like @joariasl suggested :smile:
