### ISSUE TITLE
Allow directories in the _posts

### ISSUE THREAD

**Issue by zafartahirov** [PanosSakkos/personal-jekyll-theme#136]
The subdirectories could be treated as categories, and just added to the categories list, or as blog subtopics, or both.

**Comment by PanosSakkos** [comment]
Supporting categories is tracked [here](https://github.com/PanosSakkos/personal-jekyll-theme/issues/132).
As far as I remember you can have subdirectories under the _posts directory and jekyll will parse every post recursively.

I'm closing this issue, feel free to re-open it in case I misunderstood something :smile:
