### ISSUE TITLE
Having double curly braces in the code brakes Jekyll

### ISSUE THREAD

**Issue by zafartahirov** [PanosSakkos/personal-jekyll-theme#137]
In some languages double curly braces are normal. For example in C++ `A = {{1}};` declares a two dimensional array. However if put in `<code></code>` it breaks the build process. Probably need to put `{% raw %} ... {% endraw %}`

**Comment by PanosSakkos** [comment]
I will have a look at it now.

**Comment by PanosSakkos** [comment]
The raw tags resolved it. I updated the documentation :wink:
