### ISSUE TITLE
Page title meta tag

### ISSUE THREAD

**Issue by soul-wish** [PanosSakkos/personal-jekyll-theme#139]
Hi. Please, check the `<title>` meta tag on your theme (demo). It seems like it has empty space character at the very end of line (on the pages where only `{{site.title}}` is displayed). 
Here is a screenshot:

![screen-before](https://cloud.githubusercontent.com/assets/1968098/12377182/6961d3d2-bd1c-11e5-9dad-71b666e83fb4.png)

I'm going to submit a PR with this small fix.

**Comment by njaremko** [comment]
Hahahaha, thanks for the fix 👍
