### ISSUE TITLE
Decide size of cursor in typed.js

### ISSUE THREAD

**Issue by soul-wish** [PanosSakkos/personal-jekyll-theme#141]
Hi. I hope we should increase a size of `typing cursor` in theme's `header` section. Here is my solution:
Now:
![screen-before](https://cloud.githubusercontent.com/assets/1968098/12377463/24dd458c-bd28-11e5-890f-1ddc63dc1db1.png)
After some css fixes:
![screen-after](https://cloud.githubusercontent.com/assets/1968098/12377467/46f02090-bd28-11e5-8435-6dbfcbdb88be.png)
What do you think?
PS. Also, please, check my pr regarding this issue/improvement.

**Comment by njaremko** [comment]
The font size is fine on all my displays. Also, if you wanted to make the
text bigger, you should be using something like font-size:120% instead of
changing the font.

**Comment by soul-wish** [comment]
@njaremko really strange.. I checked demo site on latest Chrome, Safari, Opera and Firefox and have the same issue in all these browsers. Cursor is much smaller than quote text (typed text). I'm on OSX (maybe that is the reason). Also, I'm not sure if we should use font-size in percentage units - quote text has size in pixels - I just duplicated it for cursor (just made it a bit smaller - it looks much better in this way).

**Comment by PanosSakkos** [comment]
I will mark it temporarily as a discussion, until I steal some time within the week (or worst case the weekend) in order to decide what we want and fix it :wink:

**Comment by wvierber** [comment]
I got the cursor in small as well (Safari and Chrome on OSX).
However, in [my fork](http://smartrunningteam.github.io) of your theme, I don't have that issue. Not sure if/what I edited when I forked.

**Comment by soul-wish** [comment]
@PanosSakkos sure! Take your time.
@wvierber you just set the same `font-size` for all the blocks/tags inside `.intro .intro-body` selector (line 214 in your grayscale.css) :wink:

**Comment by Karla-Isabel-Sandoval** [comment]
The cursor is also pretty small with Chrome Version 47.0.2526.111 (64-bit).
