### ISSUE TITLE
Disqus scripts loading

### ISSUE THREAD

**Issue by joariasl** [PanosSakkos/personal-jekyll-theme#16]
Disqus scripts are loading in the index page. It is correct?
I don't see necessary to load this scripts in this page and I recommend exclude insertion in this page. I can add the exclusion.

**Comment by PanosSakkos** [comment]
Sure, let's fix it! :)

**Comment by PanosSakkos** [comment]
The code for the disqus comments counter should be in post, blog and tag layouts. 

But, the javascript for the comments should be only in the post page, so you are correct! :)
