### ISSUE TITLE
Liquid conflict error

### ISSUE THREAD

**Issue by alexeyknorre** [PanosSakkos/personal-jekyll-theme#161]
Hey there,

got version conflict of Liquid when running serve-production:

`alexey@ubuntu:~/Jekyll/personal-jekyll-theme$ ./scripts/serve-production`
`Configuration file: /home/alexey/Jekyll/personal-jekyll-theme/_config.yml`
`/usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:2288:in 'raise_if_conflicts':` 
`Unable to activate jekyll-2.5.3, because liquid-3.0.6 conflicts with liquid (~> 2.6.1) (Gem::ConflictError)`
`	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:1408:in activate...`

Tried to manually install various version of liquid using `sudo gem install liquid -3.0.6` but no success. Do you have any ideas how to fix it? 
Thanks in advance.

**Comment by PanosSakkos** [comment]
Hi!

No I haven't seen it before. But I think it makes more sense to open the issue under the jekyll repo :wink:
