### ISSUE TITLE
Social buttons out of place

### ISSUE THREAD

**Issue by doublepmanforthewin** [PanosSakkos/personal-jekyll-theme#165]
Once I get the site running, the social buttons jump out of place. See at https://doublepmanforthewin.github.io/

**Comment by PanosSakkos** [comment]
Can you please post a screenshot? 

I visited your page but the social buttons render as expected.

**Comment by doublepmanforthewin** [comment]
![screen shot 2016-03-10 at 10 02 31 am](https://cloud.githubusercontent.com/assets/17711252/13673507/46a81964-e6a7-11e5-8af2-e10d45b7ac14.png)

**Comment by PanosSakkos** [comment]
My bad, I looked at your share buttons in the post page, not the social buttons :smile:

In the demo page they are being rendered correctly. How old is your fork? Did you make any changes?

**Comment by doublepmanforthewin** [comment]
This is a fresh fork, and the only change I've made to the original so far is updating the name, the URL, and changing the favicon....

**Comment by PanosSakkos** [comment]
I see. Then I will double check if the demo site (gh-pages branch) is up to date with Master and I will come back to you :smile:

**Comment by PanosSakkos** [comment]
The gh-pages branch is missing just one commit from master, which was a change in the travis configuration file, which cannot effect the social buttons :confused: 

Can you please try to fork the repo again?

**Comment by doublepmanforthewin** [comment]
Tried to fork again twice, same results....

**Comment by PanosSakkos** [comment]
Which client are you using to visit the website? 

Do you see the same bug in the [demo](http://panossakkos.github.io/personal-jekyll-theme) site?

**Comment by doublepmanforthewin** [comment]
Using the latest build of Chroe 64 for OS X (49.0.2623.87). I do not see the same bug in the demo.

**Comment by PanosSakkos** [comment]
ok, then I will also push the [last commit](https://github.com/PanosSakkos/personal-jekyll-theme/commit/b49407e8998d2a8aa4a9106a5f9426d4755ee3ff) from master to gh-pages, even though I don't expect that it will make any difference

**Comment by PanosSakkos** [comment]
After merging master with gh-pages I can see the regression...

**Comment by doublepmanforthewin** [comment]
Intriguing. Now, the demo site shows similar issues....

<div>-------- Original message --------</div><div>From: Panos Sakkos <notifications@github.com> </div><div>Date:03/11/2016  11:36 AM  (GMT-05:00) </div><div>To: PanosSakkos/personal-jekyll-theme <personal-jekyll-theme@noreply.github.com> </div><div>Cc: doublepmanforthewin <tcluscian@gmail.com> </div><div>Subject: Re: [personal-jekyll-theme] Social buttons out of place (#165) </div><div>
</div>After merging master with gh-pages I can see the regression...

**Comment by PanosSakkos** [comment]
Hi, I force updated the gh-pages branch from master, and now seems that the issue is resolved :smile: 

Can you please confirm it?

Thanks!

**Comment by doublepmanforthewin** [comment]
Confirmed! Thanks for your help– this is an awesome theme, and it's been an honor to contribute to its development. I'm planning to use it to build my own personal website, as well as using it for some of my clients. Starring _for sure_!

**Comment by PanosSakkos** [comment]
Thank you for reporting it! :clap: :smile:
