### ISSUE TITLE
invisible social buttons

### ISSUE THREAD

**Issue by barisaydinoglu** [PanosSakkos/personal-jekyll-theme#168]
The social buttons are invisible on Chrome.
Using the latest build of Chrome for OS X (50.0.2661.75).

There's no problem with Chrome+Windows or Safari+OSX.

Sample page: https://panossakkos.github.io

**Comment by PanosSakkos** [comment]
Hi!

Can you please post a repro screenshot? 

I couldn't repro it.

Thanks!

**Comment by barisaydinoglu** [comment]
Of course,

Chrome: ![chrome](https://cloud.githubusercontent.com/assets/900545/14930928/3ab95f46-0e70-11e6-9c5d-c4a1e4f97ddc.png)
Safari: ![safari](https://cloud.githubusercontent.com/assets/900545/14930925/36226964-0e70-11e6-8317-247e7611eeb2.png)

**Comment by PanosSakkos** [comment]
I'm on 50.0.2661.94 (64-bit) as well and I can see the social buttons.

Can you please fire up chrome's developer tools and see if there is an error logged during the loading of the page?

Thanks!

**Comment by barisaydinoglu** [comment]
I've figured out the AdBlock extension blocks the social buttons.

**Comment by PanosSakkos** [comment]
Great! :clap: 

Did you report this bug at AdBlock? :wink:
