### ISSUE TITLE
Turning off swipe between posts?

### ISSUE THREAD

**Issue by nethergrim** [PanosSakkos/personal-jekyll-theme#170]
Hi!
I'm using this theme for my personal blog, and it's awesome.
But my users don't like that feature with "swipe to change blog post", because it prevents from selecting text, sometimes.
Is it possible to turn that feature off? 
It would be awesome, thank you!

**Comment by PanosSakkos** [comment]
Hi!

Definitely, imo every feature should be toggled in order to fit everybody's needs.

The toggle for swipe navigation just slipped my radar :smile:

**Comment by BoltzmannBrain** [comment]
Hi any updates on this issue?

**Comment by PanosSakkos** [comment]
No, the plan is to do it, but there is no date set for it yet 😅

**Comment by eiselems** [comment]
@BoltzmannBrain temporally you could just delete https://github.com/PanosSakkos/personal-jekyll-theme/blob/master/_includes/js.html#L201-L270 those lines to remove the functionality altogether

Or you could just remove https://github.com/PanosSakkos/personal-jekyll-theme/blob/master/_includes/js.html#L232-L270 to just remove the popup but maintaining the ability to use swipe gestures.

HTH

@PanosSakkos would provide a PR for making it configurable but dunno if I'm able to do it - pretty busy atm
