### ISSUE TITLE
How can I left-align the text of my blog posts?

### ISSUE THREAD

**Issue by BoltzmannBrain** [PanosSakkos/personal-jekyll-theme#179]
I'd like the post title to remain centered, but then the blog text to be left-aligned. Sorry this is a question and not an issue, but I think someone looking here will know the answer easily.

**Comment by PanosSakkos** [comment]
Hi!

Can you please ask on the [gitter](https://gitter.im/PanosSakkos/personal-jekyll-theme) channel? 

You will get an answer much quicker than asking here 😉
