### ISSUE TITLE
What's the best way to add a single page?

### ISSUE THREAD

**Issue by BoltzmannBrain** [PanosSakkos/personal-jekyll-theme#182]
I would like to add a single html file as a standalone page -- not linked in the top menu bar, but linked in the About section. What is the best way to do this? My intent is to use this html file as a resume.

**Comment by PanosSakkos** [comment]
Hi @BoltzmannBrain,

I'm redirecting the questions to the [gitter channel](https://gitter.im/PanosSakkos/personal-jekyll-theme) in order to keep the issues here clear and in order for the question to be answered more quickly 😉

**Comment by BoltzmannBrain** [comment]
Sorry, I'll keep my questions to the gitter channel from now on, thanks!

**Comment by PanosSakkos** [comment]
No worries! 

Actually it was my fault. 
I [updated](https://github.com/PanosSakkos/personal-jekyll-theme/blob/master/.github/ISSUE_TEMPLATE.md) the issue template in order to notify the poster before opening the issue 👍 

Cheers,
:panos
