### ISSUE TITLE
i don't know what's wrong with my gh-pages

### ISSUE THREAD

**Issue by legolasNg** [PanosSakkos/personal-jekyll-theme#183]
i just follow what the tutorial writes.i modify the `_config.yml` as what i want.
but error occured when i accessed to my github pages.
only some words left-- "--- layout: index section-type: index sitemap: priority: 1.0 ---" 
i don't know what happened, so ask for you help.

**Comment by PanosSakkos** [comment]
Hello @legolasNg,

as the issue template states:

> Please ask your questions at the [gitter channel](https://gitter.im/PanosSakkos/personal-jekyll-theme).
> That way the issues here are kept clean and you will get an answer to your question quicker :smile:

I'm closing the issue and please ask your question in the gitter channel 😄

**Comment by PanosSakkos** [comment]
By the way I noticed that you haven't renamed your [repository](https://github.com/legolasNg/personal-jekyll-theme).

You should rename it to legolasNg.github.io 😄
