### ISSUE TITLE
Liquid Warning: Liquid syntax error (line 21): Expected id but found number in "{{ site.404-img }}" in /Users/wjl/mywork/jekyll/_layouts/error.html

### ISSUE THREAD

**Issue by ppmeng** [PanosSakkos/personal-jekyll-theme#186]
## Questions

After run "jekyll serve", the output have a warning:
Liquid Warning: Liquid syntax error (line 21): Expected id but found number in "{{ site.404-img }}" in /Users/wjl/mywork/jekyll/_layouts/error.html

I haven't change the error.html and have no idea why it happen

then I modify 404-img of_config.yml from "404-img" to "404_img" and  modify "{{ site.404-img}}" also, the warn disapper

**Comment by djcaesar9114** [comment]
You haven't modify anything from the original code and yet got this error?

**Comment by acoravos** [comment]
I'm also getting the same error. Curious if anyone has found a solution for this?

**Comment by djcaesar9114** [comment]
Again: what is your configuration and did you make any change in the code?

**Comment by acoravos** [comment]
I made changes to the `_config.yml` file. You can see all the changes here: https://github.com/codehbs/codehbs-official-homepage/blob/master/_config.yml

I didn't make any edits to the 404.html page.

**Comment by djcaesar9114** [comment]
What do `jekyll --version` and `ruby --version` give you in the terminal?
I think you may have an old version of some component and Liquid doesn't work well. On my computer the link you gave works perfectly and now I'm aware MBAs can code!

**Comment by acoravos** [comment]
My ruby version is 2.2.1 and jekyll 3.2.1.

The site also works well on the front-end / deployed, but curious why I'm seeing that error on the server side. We are going to make the website "open-source" so beginner coders can make a PR and propose changes to the site. I wanted to clean up as much on the server side as possible so newer people don't get confused when they fork/clone it locally. Any ideas?

**Comment by djcaesar9114** [comment]
Try to upgrade ruby. I have `ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]` and everything looks fine to me, I don't have any serer-side error.

**Comment by acoravos** [comment]
Hm, strange. I upgraded ruby, and I still get the server side error when running `jekyll serve`. Everything looks fine on the client side, but was hoping to clean up all errors. It's not a big deal, more curious why it's happening. 
<img width="708" alt="screenshot 2016-08-25 17 24 08" src="https://cloud.githubusercontent.com/assets/10575172/17990256/d90ee204-6ae8-11e6-9e99-dfe3aabaacd0.png">

**Comment by PanosSakkos** [comment]
Hi @ppmeng, why did you close the bug? Did you figure out what was wrong?

**Comment by PanosSakkos** [comment]
@acoravos seems like the 404 number is causing the warning. A rename on the variable should resolve that warning. Would you like to give it a try and rename the config variable?

**Comment by acoravos** [comment]
Thanks @PanosSakkos -- which variable in which file would you recommend that I change?

**Comment by djcaesar9114** [comment]
@acoravos : I created a fix. I let the owners of the repo to check it.
