### ISSUE TITLE
Option for configure main picture from social networks profile images

### ISSUE THREAD

**Issue by joariasl** [PanosSakkos/personal-jekyll-theme#206]
## Expected Behavior
Integration for configure the main picture from social networks profile images.

## Actual Behavior
Only local file picture is implemented.

## Steps to Reproduce the Issue
Inclution for:
  1. LinkedIn
  2. Facebook
  3. Twitter
  3. Gravatar

**Comment by PanosSakkos** [comment]
Excellent idea! 👏

**Comment by eiselems** [comment]
Was implemented and merged
