### ISSUE TITLE
Document how to pull changes from the repo to your local website

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#23]
It's a pain to pull changes from this repo after you have published your website.

Let's make this experience less frustrating :)

**Comment by joariasl** [comment]
1. First add remote repository if this is not added and working with the master branch:
$ `git remote add panos https://github.com/PanosSakkos/personal-jekyll-theme.git`
$ `git checkout master`
(panos name is added by the origin is other primary repository)

2. Pull request with rebase for not create a new commit:
$ `git pull --rebase panos master`
or (is equals)
$ `git fetch panos`
$ `git rebase panos master`

3. Publish changes in our fork:
$ `git push origin master`
(In case of that origin is our fork repository)

If I have time I publish myself. I am busy with my degree work. Although my English is not very good.

**Comment by joariasl** [comment]
Best use "upstream" name for original repository instead of panos. :P

**Comment by PanosSakkos** [comment]
But the idea is to document it (or provide a script) for users who have already forked a past checkpoint and they have added their own content.

For example, imagine the following scenario:

  Imagine Alice, who forked { Personal } one month ago.
  She replaced the content with hers, and she already has published posts, has her own _config.yml etc.

The goal is to make it very easy for Alice to integrate all the features and the bug fixes that we have in the repo (i.e.) today, into her website, without losing her content ;)

I'm busy to tackle this and I want first to fix issue #25.
So feel free to work in this issue in your free time! :)

**Comment by PanosSakkos** [comment]
Added this guy 2d18f0ad3eccb21c04397268d0c7d2542c5cffcc and used it to integrate the latest changes into my website and it worked.

The only caveat is that if there are you miss the site config changes, because this file contains user's data, plus (probably) new configuration features.
So when you actually use this script, you need to run a diff between the two site configs, and then migrate manually the newly added configuration options.

I will document it in the wiki as carefully as I can :)

**Comment by PanosSakkos** [comment]
Added the documentation [here](https://github.com/PanosSakkos/personal-jekyll-theme/wiki/How-to-integrate-latest-bug-fixes-and-features-into-your-past-fork).

Feel free to give me feedback on the steps from a user's perspective ;)

**Comment by joariasl** [comment]
I make the gh-pages branch and modify this with my personal configuration. When I modify the main features I change to master branch and merge to gh-pages. 
So I keep a clean code and I send a pull request.

**Comment by PanosSakkos** [comment]
Sure, but you are doing this in order to contribute to the { Personal } repository.

My purpose was to help users who have downloaded { Personal } and put it in a different X.github.io repository (i.e.), and they want to pull the latest changes from the official { Personal } repository ;)
