### ISSUE TITLE
Deprecation: jekyll-paginate will be retired from Jekyll 3

### ISSUE THREAD

**Issue by altsheets** [PanosSakkos/personal-jekyll-theme#33]
Thanks a lot for your great theme!
A small issue:

    gem install jekyll-paginate
    jekyll serve 

    Configuration file: /var/www/.../personal-jekyll-theme/_config.yml
           Deprecation: You appear to have pagination turned on, 
           but you haven't included the `jekyll-paginate` gem. 
           Ensure you have `gems: [jekyll-paginate]` in your configuration file.

I found this:

    jekyll-paginate will be retired from Jekyll 3. I'd recommend using Octopress Paginate
https://talk.jekyllrb.com/t/build-problem-missing-post/1241/4

HTH
:-)

**Comment by PanosSakkos** [comment]
You 're welcome!

I noticed it as well, and I'm trying to fix it asap :disappointed:
