### ISSUE TITLE
Multiple pagination links

### ISSUE THREAD

**Issue by jose-zama** [PanosSakkos/personal-jekyll-theme#34]
Hello,

There is a tiny bug with pagination.

**Issue**: When having more than 2 pages, the pagination shows two "newer posts" links and two "older posts" links. 

![badpagination](https://cloud.githubusercontent.com/assets/10884160/10862063/cedbee56-7f5e-11e5-8b82-d937aa89591a.png)

**Proposed Solution**: Update pagination.html to:

```html
<div class="pagination">

  <h4>
 
  {% if paginator.previous_page %}
    <a href="{{site.baseurl}}{{ paginator.previous_page_path }}" class="previous">Newer Posts</a>
  {% endif %}

  {% if paginator.next_page %}
    <a href="{{site.baseurl}}{{ paginator.next_page_path }}" class="next">Older Posts</a>
  {% endif %}
  
  </h4>
  
</div>
```

**Comment by PanosSakkos** [comment]
That's a regression! Well spotted! :smile:
