### ISSUE TITLE
Make images reponsive

### ISSUE THREAD

**Issue by jose-zama** [PanosSakkos/personal-jekyll-theme#36]
Hello,

This is more a suggestion than a bug.

Currently, I am adding images into my posts through markdown syntax and this theme does not resize the images if opened in a mobile browser. I think Jekyll has responsive images by default. Here the comparison:

**No responsive images**

![imagesnotresponsive](https://cloud.githubusercontent.com/assets/10884160/10862376/d469988a-7f6a-11e5-974d-a00435b659e4.png)

**Responsive images**

Using:

```css
img {
    max-width: 100%
}
```

![imagesresponsive](https://cloud.githubusercontent.com/assets/10884160/10862377/e326087c-7f6a-11e5-9c48-6cae0f7f0e84.png)

In the case the user cant properly see the image, they can zoom with no problem (tested only in my mobile: android with chrome).

**Comment by PanosSakkos** [comment]
Awesome! It was on my list the early days, but I didn't take a note of it and of course I forgot it :smile:

Was fixed by your pull request 07bb6ad5aad597815b29dc58027f2e049266aeb6
