### ISSUE TITLE
Add LinkedIn share button

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#38]

**Comment by njaremko** [comment]
But a linkedin share button is already possible with 
- title: "linkedin"<br>
url: "https://ca.linkedin.com/in/your-username"

Are you just including it by default now?

**Comment by PanosSakkos** [comment]
I meant share button for the posts :wink:

**Comment by chipset95** [comment]
Added in #43 

@PanosSakkos Please have a look

**Comment by PanosSakkos** [comment]
@chipset95 That's great! :smile: 

P.S.: I'm at the office right now and later I'm flying abroad for the weekend, so I will manage to review it on Sunday afternoon (GMT +1 is my TZ)

Thanks for the initiative!

**Comment by chipset95** [comment]
This was fun :)
