### ISSUE TITLE
Sections are displayed sorted on title

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#40]
Reported by @chipset95 .

**Comment by PanosSakkos** [comment]
@chipset95 actually I had a look at the code and the sections are hardcoded, and the navigation bar is not sorted on section tile (I fixed that actually after I forked the timeline repository).

So if someone wants to change the order of the section, he/she has to edit the includes/index.html, which is reasonable given that this the intention is by definition a hard change in the theme :smile:

I'm closing this issue.

**Comment by chipset95** [comment]
I didn't get it. There is no index.html in includes. Also, where are the sections being hardcoded?

**Comment by PanosSakkos** [comment]
My bad, it's the index.html layout :smile:

**Comment by chipset95** [comment]
I've tried changing the order in `_layouts/index.html` But the order remain to be About, Blog, Career, Contact.

Just tried it again.

**Comment by PanosSakkos** [comment]
You mean that the order in the navigation bard remained the same? 

The navigation bar is ordered based on the order that the list in the _config.yml is declared.

**Comment by chipset95** [comment]
I'm able to change the order in the navigation bar from _config.yml, but I want to change the order in index.html to match the order in navigation bar. 

I have this in index.html under layouts right now

```ruby
<!-- Index Layout Start -->

<!DOCTYPE html>
<html lang="{{ site.lang }}">

  {% include head.html %}

  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    {% include navigation.html %}

    {% include header.html %}

    {% for page in site.pages %}

      {% if page.section-type == "about" %}

        {% include about.html %}

      {% elsif page.section-type == "work" %}

        {% include work.html %}

      {% elsif page.section-type == "contact" %}

        {% include contact.html %}

      {% elsif page.section-type == "latest-post" %}

        {% include latest-post.html %}

      {% endif %}

    {% endfor %}

    {% include footer.html %}

    {% include js.html %}

  </body>
</html>

<!-- Index Layout End -->
```

And the result of this can be seen [here](http://chispet95.github.io)

**Comment by PanosSakkos** [comment]
I see. Yes it makes sense, given that they are being rendered based on the order that they exist in the site.pages.

We should be smarter, I think we should iterate over the navigation items, given that each section should anyway be listed in the navigation bar :smile: 

Re-opening the issue as a bug.

**Comment by joariasl** [comment]
Exists a problem obtain each page if not use `{% for page in site.pages %}`
I intent obtain the _include file using:
```yaml
    {% for p in site.pages_list %}
      {% if p == "blog" %}
        {% include latest-post.html %}
      {% else %}
        {% include about.html %}
      {% endif %}
    {% endfor %}
```
But I do not know as obtain the specific content for the page (for example in about.html in the root path).

The Blogs item is different to the file name, because I added an exeption:
```
Pages in Home:
'about' => about.html
'blog' => latest-post.html (X)
'career' => career.html
'contact' => contact.html
```

I don't know many YAML. ¿Any idea for solve this?

**Comment by joariasl** [comment]
Fixed in my latest pull request with:
```
    {% for p in site.pages_list %}
      {% for page in site.pages %}
        {% if p[1] == page.section-type%}
          {% include {{ page.path }} %}
        {% endif %}
      {% endfor %}
    {% endfor %}
```
