### ISSUE TITLE
List of social buttons?

### ISSUE THREAD

**Issue by altsheets** [PanosSakkos/personal-jekyll-theme#41]
The post https://github.com/PanosSakkos/personal-jekyll-theme/blob/master/_posts/2015-06-11-social-buttons-tutorial.md says "just try them out".

Perhaps there is a list somewhere?

And how to extend them, to include more?

I would like additional buttons for 
* bitcointalk.org
* startpeeps.com
* Diaspora
* nxtforum.org

Thanks!

**Comment by chipset95** [comment]
The social links follow the naming convention in [Font Awesome icon gallery](https://fortawesome.github.io/Font-Awesome/icons/)

e.g. If you want to add the bitcoin icon in the social buttons, the following code snippets will help

**_config.yml**
```
- title: "btc"
    url: "yoururl.com"
```

I've noticed that this will try to find the class "fa fa-btc" in font awesome css and render the appropriate icon. Unfortunately, not all icons are available in font awesome.

**Comment by PanosSakkos** [comment]
@chipset95 That's correct :smile: 

I will update the documentation post when time permits (or feel free to chip in :wink: )

**Comment by altsheets** [comment]
> The social links follow the naming convention in Font Awesome icon gallery
Ahhhh. Great. That helped.

For the time being, I just use other icons, until the real ones become part of FA.

Thanks a lot!

**Comment by PanosSakkos** [comment]
I'm re-opening the issue because it should be part of the documentation :wink:

**Comment by chipset95** [comment]
I'll update the post soon.
