### ISSUE TITLE
writable area decreases when window 1199px --> 1200px (workaround provided)

### ISSUE THREAD

**Issue by altsheets** [PanosSakkos/personal-jekyll-theme#48]
for some reason, the writable area

    .content-section .row .(col-lg-8 col-lg-offset-2)

decreases(!) from 970px width to 780px width
when the window size *increases* from 1199px to 1200px.

Not sure why (I am not an experienced CSS designer),
but this workaround fixed it for me:

    @media(min-width:1200px){
    	.content-section .col-lg-8 {
    	    width:970px;
    		margin-left:100px;
    		margin-right:auto;
    	}
    }

HTH

:-)

**Comment by PanosSakkos** [comment]
Hmm I'm sorry but I don't get what you mean by "writeable area".

Can you please post screenshot/s to reproduce it?

I'm asking because we should understand the issue in order to fix it :wink:

**Comment by altsheets** [comment]
> what you mean by "writeable area".  

The area that the text is rendered into.
It gets *smaller* when the whole window gets *larger*.

> screenshot/s  

Sure, no problem. Here:
http://i.imgur.com/YoVGbRR.png

Hope that helps :-)


P.S.: Using your theme as the basis for my new website (https://github.com/PanosSakkos/personal-jekyll-theme/issues/46#issuecomment-154876313). Thanks a lot :-)

**Comment by PanosSakkos** [comment]
Oh I see what you mean.. 
I'm also new to CSS and I have no idea why this is happening.. But it's great that you have a fix! :smile: 

Our CSS champion is @joariasl by the way. @joariasl any ideas why this is happening? :sweat: 

@altsheets Can you please open a pull request with your suggestion in order to test it and merge it with the repo? :wink: 

P.S.: Your website looks great! :wink:

**Comment by joariasl** [comment]
This week I think that I have more free time. It is easy to fix. I will take a time to implement other improvements.

**Comment by PanosSakkos** [comment]
@altsheets that's why we call him the CSS champion of the repo! :stuck_out_tongue_winking_eye: :clap:

**Comment by altsheets** [comment]
>  It is easy to fix.   

Nice. Happy to hear.

> open a pull request with your suggestion  

Not sure that is necessary.
All that needs to be added is up there in the OP.

---

Ah ... another good idea, to operationalize this, and to keep it clean.

1) add two more css files, call them   
* personal.css, and  
* user.css  
  
2) load both by default from the html. (BELOW ... link href="grayscale.css and timeline.css )
  
3) 
put all your "personal-jekyll-theme" CSS changes into personal.css. And suggest to users / forkers ... to put their additional styles into user.css !
  
Then you can import the unchanged(!) grayscale.css and timeline.css *from their original sources*, and all your "personal-jekyll-theme" specific CSS will just override those. The advantage: If there are newer, updated commits of the original grayscale.css / timeline.css it will be really easy to merge them into PJT.
Plus, the end users (like me), will know where to put their style changes. 

In my case, I had just added an "altsheets.css" into [line 31](https://github.com/PanosSakkos/personal-jekyll-theme/blob/84b054b0ce580ea4a7f86454aed494f846e057e3/_includes/head.html#L31), and put all my style changes into that file. This way I could keep your .CSS unchanged. 

And CSS that is loaded later, will override CSS that is loaded earlier (I looked that up * g * ).


> But it's great that you have a fix!  

Happy to help. Cooperation ... that is best aspect of the internets.


> P.S.: Your website looks great!   

Thanks a lot. Yours, too * lol *

**Comment by PanosSakkos** [comment]
Fixed here commit/004cf1f53e341b68ab9d80f11b290f2249ce34fe

**Comment by altsheets** [comment]
>> col-lg-8 col-lg-offset-2

> col-lg-10 col-lg-offset-1

ah, that makes sense. 

I had actually already suspected s.th. like that, 
but I had not fully understood the underlying CSS.

Cool. Thanks a lot

**Comment by altsheets** [comment]
and what about the idea to leave the original   

    grayscale.scss
    Grayscale Bootstrap Theme (http://startbootstrap.com)

untouched, and just *override* it with a (later-loaded)

    personal-jekyll-theme.css

in which all the local changes are kept together?

See the 2nd part of https://github.com/PanosSakkos/personal-jekyll-theme/issues/48#issuecomment-155183980

For now, it might be a bit of a hassle, but a good compare-tool will make it easy. Long-term it is definitely of advantage.

Thanks for considering it.

**Comment by joariasl** [comment]
The original grayscale style contains any bugs not corrected.
I created a pull request for this project, but the project is apparently abandoned.
https://github.com/IronSummitMedia/startbootstrap-grayscale/pull/27

Another person saw the same errors:
https://github.com/IronSummitMedia/startbootstrap-grayscale/pull/18
