### ISSUE TITLE
Not centering blog post text?

### ISSUE THREAD

**Issue by woosley** [PanosSakkos/personal-jekyll-theme#49]
Hello!
I am just wondering is there any good reason to center the blog post text? which seems not a good way to display an "article". is it possible to make text in blog posts left aligned by default?

**Comment by njaremko** [comment]
It's centred to fit with the theme of the site. If you want to have it left justified, just go into the blog file in the layouts folder, and change:
```<section id="{{ page.title }}" class="container content-section text-center">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          {% include social-buttons.html %}
        </div>
      </div>
    </section>```

to 

```
<section id="{{ page.title }}" class="container content-section text-left">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          {% include social-buttons.html %}
        </div>
      </div>
    </section>
```

**Comment by PanosSakkos** [comment]
@woosley It was like this in the original [repo](https://github.com/kirbyt/timeline-jekyll-theme) that I forked and I just liked it like, no other specific reason :smile: 

Feel free to make is as you like in your local repo by following @njaremko 's direction :wink:
