### ISSUE TITLE
Bad generation of ID in Post pages

### ISSUE THREAD

**Issue by joariasl** [PanosSakkos/personal-jekyll-theme#57]
In the files:
* post.html
* lastest-post.html
, the line:
```yml
<section id="{{ page.title }}" class="container content-section text-center">
```
generate a not correctly id in the HTML element. This like losing semantic for search engines and is an error.

The ID format for HTML element with more of one word is (For convention in lowercase): `word1-word2-word3`
 Image with the actual result:
![id_problem](https://cloud.githubusercontent.com/assets/8829064/11110233/15ca3cdc-88d8-11e5-8513-de1b4955b712.png)

Must be applied the same process that when is generate the ID in the Markdown high level title (removing special chars):
![id_problem2](https://cloud.githubusercontent.com/assets/8829064/11110356/91c0b72a-88d9-11e5-8e66-563d93945009.png)

**Comment by PanosSakkos** [comment]
Great catch! :wink: :+1:

**Comment by joariasl** [comment]
Is fixed in my pull request #56.

**Comment by PanosSakkos** [comment]
I noticed it, I will continue the PL tonight or tomorrow :smile:

**Comment by joariasl** [comment]
I finished my contribution for now. :smille:
