### ISSUE TITLE
Go through the documentation posts to see if they are up to date

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#64]

**Comment by eiselems** [comment]
I think the this would be a good opportunity to add some details about the intended usage of the integration script.

**Comment by PanosSakkos** [comment]
Yes, I plan to document our version numbers an explain when the integration is broken :smile: 

Because lately there have been very heavy changes, so an old fork is impossible to integrate with the repo's :disappointed_relieved:

**Comment by PanosSakkos** [comment]
@eiselems I think the [integration instructions](https://github.com/PanosSakkos/personal-jekyll-theme/wiki/Integrating-latest-bug-fixes-and-features-into-your-past-fork) are more clear now :smile:
