### ISSUE TITLE
Change Copyright to Creative Commons

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#65]

**Comment by altsheets** [comment]
Take care of the old users, who rely on MIT. Perhaps branches are a way to go.

[This project](https://github.com/etherparty/explorer) for example has decided to switch from MIT to GPL, and they decided to leave their old v0.1.0 code as a "[MIT branch](https://github.com/etherparty/explorer/tree/MIT)".

HTH :-)

**Comment by njaremko** [comment]
Is there a reason why we're changing licenses?

**Comment by PanosSakkos** [comment]
I just thought that CC is more suitable. If it makes things complicated we can just drop it :sweat_smile:
