### ISSUE TITLE
Create SEO XML or text file for indexation in search engines

### ISSUE THREAD

**Issue by joariasl** [PanosSakkos/personal-jekyll-theme#66]
https://support.google.com/webmasters/answer/183668

**Comment by PanosSakkos** [comment]
Great suggestion, let's take it in the milestone :smile:

**Comment by joariasl** [comment]
This will help: http://davidensinger.com/2013/03/generating-a-sitemap-in-jekyll-without-a-plugin/

**Comment by PanosSakkos** [comment]
@joariasl Don't forget to comment on the issues that you are working on, in order to avoid duplicate work :wink:

**Comment by joariasl** [comment]
Completed! I create a PL some
