### ISSUE TITLE
Emoji Support

### ISSUE THREAD

**Issue by chipset95** [PanosSakkos/personal-jekyll-theme#70]
Options available:
- [Twemoji](http://blog.farrant.me/adding-emoji-support-to-any-website/)
- [Twemoji Awesome](http://ellekasai.github.io/twemoji-awesome/)
- [Emojione](http://emojione.com/)

@PanosSakkos I guess this won't be a milestone 4 feature? Also, add the appropriate labels please. :smile:

**Comment by PanosSakkos** [comment]
We have plenty of time until xmas, so let's take it in! :wink:

**Comment by chipset95** [comment]
Cool :)
