### ISSUE TITLE
Replace javascript redirection to https with html

### ISSUE THREAD

**Issue by PanosSakkos** [PanosSakkos/personal-jekyll-theme#72]

**Comment by joariasl** [comment]
if the exception is maintained for localhost it will not be possible.

**Comment by PanosSakkos** [comment]
But we can use a Liquid condition, like we are doing currently with the javascript approach, right?

**Comment by joariasl** [comment]
Exact. If siteurl is localhost or 127.0.0.1 ignore this.

**Comment by PanosSakkos** [comment]
Now I got what you meant. 
In built time we don't know what is the current url, of course :smile: 

I propose to leave the redirection as it is now, because it's a hack but it's the most transparent way for the user to use.

**Comment by joariasl** [comment]
The HTML tag redirecton is not possible. Because the site would to fail in an infinite cycle, being that a static redirection and this not detect the use or not of HTTPS protocol.

**Comment by PanosSakkos** [comment]
Yes :) :+1:
