### ISSUE TITLE
Incorrect start_url

### ISSUE THREAD

**Issue by chipset95** [PanosSakkos/personal-jekyll-theme#98]
`start_url` in `manifest.json` inside `_site` if empty is `baseurl` is kept empty in `_config.yml`

Suggestion for fix:

Change `"start_url": "{{site.baseurl}}"` to `"start_url": "{{site.url}}{{site.baseurl}}"`

**Comment by PanosSakkos** [comment]
I saw that bug yesterday after I integrated the changes into my website, which doesn't have a baseurl :confused: 

Your change seems correct, but I have to test it on my Android, so I will do it later tonight, because I left it home :yum: 

Good catch! :smile:
